// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * uic_uiLabelPRESS;
lv_obj_t * uic_Panel3;
lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_Panel3 = NULL;
lv_obj_t * ui_uiLabelHR = NULL;
lv_obj_t * ui_uiLabelTEMP = NULL;
lv_obj_t * ui_uiLabelPRESS = NULL;
// event funtions

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel3 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel3, lv_pct(100));
    lv_obj_set_height(ui_Panel3, lv_pct(100));
    lv_obj_set_x(ui_Panel3, -1);
    lv_obj_set_y(ui_Panel3, -1);
    lv_obj_set_align(ui_Panel3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel3, lv_color_hex(0x121010), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_uiLabelHR = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_uiLabelHR, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_uiLabelHR, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_uiLabelHR, -75);
    lv_obj_set_y(ui_uiLabelHR, 121);
    lv_obj_set_align(ui_uiLabelHR, LV_ALIGN_CENTER);
    lv_label_set_text(ui_uiLabelHR, "HR:---bpm");
    lv_obj_set_style_text_color(ui_uiLabelHR, lv_color_hex(0xF31515), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_uiLabelHR, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_uiLabelTEMP = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_uiLabelTEMP, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_uiLabelTEMP, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_uiLabelTEMP, lv_pct(25));
    lv_obj_set_y(ui_uiLabelTEMP, lv_pct(43));
    lv_obj_set_align(ui_uiLabelTEMP, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_uiLabelTEMP, LV_LABEL_LONG_SCROLL_CIRCULAR);
    lv_label_set_text(ui_uiLabelTEMP, "Temp:----C");
    lv_obj_set_style_text_color(ui_uiLabelTEMP, lv_color_hex(0x15F349), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_uiLabelTEMP, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_uiLabelPRESS = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_uiLabelPRESS, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_uiLabelPRESS, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_uiLabelPRESS, lv_pct(-26));
    lv_obj_set_y(ui_uiLabelPRESS, lv_pct(30));
    lv_obj_set_align(ui_uiLabelPRESS, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_uiLabelPRESS, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_uiLabelPRESS, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_label_set_text(ui_uiLabelPRESS, "Press:-------hpa");
    lv_obj_set_style_text_color(ui_uiLabelPRESS, lv_color_hex(0xE3BB13), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_uiLabelPRESS, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    uic_Panel3 = ui_Panel3;
    uic_uiLabelPRESS = ui_uiLabelPRESS;

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    uic_Panel3 = NULL;
    ui_Panel3 = NULL;
    ui_uiLabelHR = NULL;
    ui_uiLabelTEMP = NULL;
    uic_uiLabelPRESS = NULL;
    ui_uiLabelPRESS = NULL;

}
